services:
  postgres_dev:
    networks:
      dev_net:
        aliases:
          - postgres
    image: postgres:15
    container_name: Fin-PostgresDB-DEV
    restart: "no"
    env_file:
      - .env.dev
    environment:
      TZ: Europe/Zurich
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database/init_fin_schema.sql:/docker-entrypoint-initdb.d/01_fin_init.sql
      - ./database/dev_fin_data_seed.sql:/docker-entrypoint-initdb.d/02_fin_dummy_data.sql
    ports:
      - "5432:5432"
    healthcheck:  # TODO complex healthcheck that tests db/table existence
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend_dev:
    networks:
      dev_net:
        aliases:
          - backend
    build:
      context: ./backend
    container_name: Fin-fastAPI-DEV
    restart: "no"
    env_file:
      - .env.dev
    environment:
      TZ: Europe/Zurich
    ports:
      - "8000:8000"
    depends_on:
      postgres_dev:
        condition: service_healthy

  frontend_dev:
    networks:
    - dev_net
    build:
      context: ./frontend
    container_name: Fin-Vue-DEV
    restart: "no"
    environment:
      TZ: Europe/Zurich
    ports:
      - "5173:5173"
    depends_on:
      - backend_dev

volumes:
  postgres_data_dev:

networks:
  dev_net:
